#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret=$(ynh_string_random --length=16)

ynh_app_setting_set --key="secret" --value="$secret"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/log" "$install_dir/tmp/pids" "$install_dir/tmp/sockets"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration file..."

ynh_config_add --template=".env.example" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir"
	cp config/unicorn.rb.example config/unicorn.rb
	chown -R "$app:www-data" "$install_dir/config/unicorn.rb"
	gem install rubygems-update -v 3.4
	gem update --system --no-document
	gem install bundler -v 2.4.22
	gem install rake foreman --no-document
	bundle config set --local deployment 'true'
	bundle config set --local without 'development test'
	bundle install
	ynh_hide_warnings bundle exec rake db:create RAILS_ENV=production
	ynh_hide_warnings bundle exec rake db:migrate RAILS_ENV=production
	ynh_hide_warnings bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=$admin SEED_PASSWORD=$password
	ynh_hide_warnings bundle exec rake assets:precompile RAILS_ENV=production
popd

chmod 750 "$install_dir/public"
chmod -R o-rwx "$install_dir/public"
chown -R "$app:www-data" "$install_dir/public"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="$app-web" --template="web.service"
yunohost service add "$app-web" --log="$install_dir/log/unicorn.log"

ynh_config_add_systemd --service="$app-jobs" --template="jobs.service"
yunohost service add "$app-jobs" --log="$install_dir/log/production.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

# Start a systemd service
ynh_systemctl --service="$app-web" --action="start" --log_path="$install_dir/log/unicorn.log" --wait_until="listening on addr"
ynh_systemctl --service="$app-jobs" --action="start" --log_path="$install_dir/log/huginn-jobs.log" --wait_until="Starting"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
