#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_ruby__2
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

secret=$(ynh_string_random --length=16)

ynh_app_setting_set --app=$app --key=secret --value=$secret

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..."

ynh_install_ruby --ruby_version=$ruby_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/log" "$install_dir/tmp/pids" "$install_dir/tmp/sockets"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

ynh_add_config --template="../conf/.env.example" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..."

pushd $install_dir
	ynh_use_ruby
	cp config/unicorn.rb.example config/unicorn.rb
	chown -R $app:www-data "$install_dir/config/unicorn.rb"
	ynh_gem update --system --no-document
	ynh_gem install rake bundler foreman --no-document
	bundle config set --local deployment 'true'
	bundle config set --local without 'development test'
	bundle install
	ynh_exec_warn_less bundle exec rake db:create RAILS_ENV=production
	ynh_exec_warn_less bundle exec rake db:migrate RAILS_ENV=production
	ynh_exec_warn_less bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=$admin SEED_PASSWORD=$password
	ynh_exec_warn_less bundle exec rake assets:precompile RAILS_ENV=production
popd

chmod 750 "$install_dir/public"
chmod -R o-rwx "$install_dir/public"
chown -R $app:www-data "$install_dir/public"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..."

# Create a dedicated systemd config
ynh_add_systemd_config --service="$app-web" --template="web.service"
ynh_add_systemd_config --service="$app-jobs" --template="jobs.service"

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add "$app-web" --log="$install_dir/log/unicorn.log"
yunohost service add "$app-jobs" --log="$install_dir/log/production.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name="$app-web" --action="start" --log_path="$install_dir/log/unicorn.log" --line_match="listening on addr"
ynh_systemd_action --service_name="$app-jobs" --action="start" --log_path="$install_dir/log/huginn-jobs.log" --line_match="Starting"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
