#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi

ynh_config_remove_systemd"$app-web"

if ynh_hide_warnings yunohost service status "$app-jobs" >/dev/null; then
    yunohost service remove "$app-jobs"
fi

ynh_config_remove_systemd"$app-jobs"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
