#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

mkdir -p "$install_dir/log" "$install_dir/tmp/pids" "$install_dir/tmp/sockets"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir"
	gem install rubygems-update -v 3.4
	gem update --system --no-document
	gem install bundler -v 2.4.22
	gem install rake foreman --no-document
	bundle config set --local deployment 'true'
	ynh_hide_warnings bundle config set --local without 'development test'
	ynh_hide_warnings bundle install
	ynh_hide_warnings bundle exec rake assets:clean assets:precompile tmp:cache:clear RAILS_ENV=production
popd

chmod 750 "$install_dir/public"
chmod -R o-rwx "$install_dir/public"
chown -R "$app:www-data" "$install_dir/public"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-web.service"
systemctl enable "$app-web.service" --quiet
yunohost service add "$app-web" --log="$install_dir/log/unicorn.log"

ynh_restore "/etc/systemd/system/$app-jobs.service"
systemctl enable "$app-jobs.service" --quiet
yunohost service add "$app-jobs" --log="$install_dir/log/production.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-web" --action="start" --log_path="$install_dir/log/unicorn.log" --wait_until="listening on addr"
ynh_systemctl --service="$app-jobs" --action="start" --log_path="$install_dir/log/huginn-jobs.log" --wait_until="Starting"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
