#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd services..."

ynh_systemctl --service="$app-web" --action="stop"

ynh_systemctl --service="$app-jobs" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"
mkdir -p "$install_dir/log" "$install_dir/tmp/pids" "$install_dir/tmp/sockets"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env.example" --destination="$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir
	cp -f config/unicorn.rb.example config/unicorn.rb
	chown -R "$app:www-data" "$install_dir/config/unicorn.rb"
	gem install rubygems-update -v 3.4
	gem update --system --no-document
	gem install bundler -v 2.4.22
	gem install rake foreman --no-document
	bundle config set --local deployment 'true'
	bundle config set --local without 'development test'
	bundle install
	ynh_hide_warnings bundle exec rake db:migrate RAILS_ENV=production
	ynh_hide_warnings bundle exec rake assets:clean assets:precompile tmp:cache:clear RAILS_ENV=production
popd

chmod 750 "$install_dir/public"
chmod -R o-rwx "$install_dir/public"
chown -R "$app:www-data" "$install_dir/public"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-web" --template="web.service"
yunohost service add "$app-web" --log="$install_dir/log/unicorn.log"

ynh_config_add_systemd --service="$app-jobs" --template="jobs.service"
yunohost service add "$app-jobs" --log="$install_dir/log/production.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-web" --action="start" --log_path="$install_dir/log/unicorn.log" --wait_until="listening on addr"
ynh_systemctl --service="$app-jobs" --action="start" --log_path="$install_dir/log/huginn-jobs.log" --wait_until="Starting"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
